name: Validate YAML data files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # See https://github.com/marketplace/actions/yaml-schema-validator
    - uses: nwisbeta/validate-yaml-schema@v1.0.3
